# Generated by Django 5.2.1 on 2025-05-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
    ]
