# Generated by Django 5.2.1 on 2025-05-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='stock',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/procedure/Y/%m/%d'),
        ),
    ]
